---
title: 'R: Presenting unlimited power for statistics'
author: "Dmitrij Petrov, Jeanne Falonne Magne Signe, Mesut Sahin, Rahman Gökbulut"
date: "25.6.2015"
output:
  ioslides_presentation:
    fig_height: 6
    fig_width: 8
    logo: /srv/shiny-server/SemesterProject/Presentations/pictures/hs_logo_besser.png
    smaller: yes
    transition: faster
    widescreen: yes
  slidy_presentation:
    highlight: zenburn
---

## Agenda | 24 Folien | 15 Minuten | 4 Menschen | 1 Resultat

1. Einführung in das Projekt
2. Einführung ins R
3. Unseren Datensatze
4. Explorative Datenanalyse (EDA)
5. Resultate

## Einführung in das Projekt

```{r}

```


## Einführung ins R


## Read, Load and Parse Excel dataset

```{r}
library(xlsx)
dataset.S <- read.xlsx("/srv/shiny-server/SemesterProject/Data/DataSet_01.xlsx", sheetIndex = 1, endRow=277)
dataset.P <- read.xlsx("/srv/shiny-server/SemesterProject/Data/DataSet_Product.xlsx", sheetIndex = 1, endRow=302)

```


## Danke

PS: Presentation wurde mit [R Markdown](http://rmarkdown.rstudio.com/) erstellt.


