graph TD
  A-->B[Einarbeitung in R]
  B-->H[u.a.  z.B. in Shiny]
  A-->C[Explorative Datenanalyse]
  C-->D[Korrelation]
  D-->E[Normalverteilung]
  E-->F[Potenz Transformation]
  F-->G[Regression]
  H-->I[Ende]